apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    service: django
spec:
  selector:
    app: django
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30000
    port: 8000
    protocol: TCP
    targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer