apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      targetPort: 8000
      protocol: TCP
      port: 8000
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: Cluster

